Merged PR 12437: Use TransactionMgmt/CommonRefTypes for adjustmentQuantity
The current Tibco app for Inventory Spoilage **wrongly** uses the namespace `http://schemas.wfm.com/Enterprise/TransactionMgmt/CommonRefTypes/V1` for the `adjustmentQuantity` element, instead of `http://schemas.wfm.com/Enterprise/InventoryMgmt/CommonRefTypes/V1`. [Refer](https://dev.azure.com/wholefoods/Supply%20Chain%20Application%20Development/_git/SCAD?path=/Icon/Tibco/PublishInventorySpoilageService/Processes/PublishInventorySpoilageService.process&version=GBmaster&line=97&lineEnd=113&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents).

In the rewritten service, I tried using the correct namespace, and it is successfully being parsed by the data processors (wormhole consumers). However, when I tested end to end, by publishing to ESB, the data was not received by the wormhole. This is because it is failing due to a validation added by the DDS team in the Java bridge that is responsible for sending data to wormhole. The validation fails with the error,
```
Job-84294 Error in [Processes/Starter/InventoryAdjustment.process/ParseInventoryXML]
A validation occurred while parsing:  validation error: unexpected content "{http://schemas.wfm.com/Enterprise/InventoryMgmt/CommonRefTypes/V1}quantity"; expected "{http://schemas.wfm.com/Enterprise/TransactionMgmt/CommonRefTypes/V1}quantity"   ({com.tibco.xml.validation}COMPLEX_E_UNEXPECTED_CONTENT) at /inventoryAdjustments[1]/inventoryAdjustment[1]/inventoryAdjustmentDetail[1]/adjustmentQuantity[1]/ns0:quantity[1]
com.tibco.xml.validation.exception.UnexpectedElementException: unexpected content "{http://schemas.wfm.com/Enterprise/InventoryMgmt/CommonRefTypes/V1}quantity"; expected "{http://schemas.wfm.com/Enterprise/TransactionMgmt/CommonRefTypes/V1}quantity"
```
Basically, the validation is also expecting the wrong namespace.

Introducing a hack to modify the auto generated file, WfmContracts.cs (the class used by new service for generation of the canonical), to use the `TransactionMgmt/CommonRefTypes/V1` namespace. As, if we don't do it, wormholes will not receive the data.

We can come back at this change, once the consumers have moved away from wormholes.

Next step: Update the version of `Icon.Esb.Schemas.Wfm` in the InventoryProducer.sln project, once this PR is merged and built.

Related work items: #51252